# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cache-Memcached-Semaphore
version:      0.3
version_from: Semaphore.pm
installdirs:  site
requires:
    Cache::Memcached:              0
    Digest::MD5:                   0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
